name: "Assign reviewers"

on: pull_request

jobs:
  add-reviewer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ohnogumi/auto-reviewers@v0.0.5
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
