jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        name: Create Pull Request
        # Creates a PR from current branch to master
        run: |
          gh pr create --base master --head origin/${GITHUB_REF#refs/heads/} --fill
name: Create Pull Request
on:
  push:
    branches:
      - "translation/*"
      - "update/*"
