jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Fetch master
        run: git fetch origin master
      - env:
          GH_TOKEN: ${{ secrets.CONTENT_GITHUB_TOKEN }}
        name: Create Pull Request
        # Creates a PR from current branch to master
        run: |
          gh pr create --base master --head ${GITHUB_REF#refs/heads/} --fill
name: Create Pull Request
on:
  push:
    branches:
      - "translation/*"
      - "update/*"
