name: size-label
on: pull_request
jobs:
  size-label:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: size-label
        uses: "webdoky/size-label-action@main"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
  assign-reviewers:
    needs: [size-label]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - id: determine-reviewers-needed
        name: Determine if reviewers are needed
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          LABELS=$(gh pr view $PR_NUMBER --json labels --jq '.labels[].name')
          REVIEWER="${{ github.repository_owner }}/translators"

          if [[ $LABELS == *"size/XS"* ]] || [[ $LABELS != *"size/"* ]]; then
            echo 'No review'
          else
            echo "add_reviewers=true" >> $GITHUB_OUTPUT
          fi
        env:
          GH_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - name: Add reviewers
        if: steps.determine-reviewers-needed.outputs.add_reviewers == 'true'
        uses: madrapps/add-reviewers@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          reviewers: ${{ github.repository_owner }}/translators
