name: size-label
on: pull_request_target
jobs:
  size-label:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: size-label
        uses: "webdoky/size-label-action@main"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
  assign-reviewers:
    needs: [size-label]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Assign/Remove reviewers based on size label
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          LABELS=$(gh pr view $PR_NUMBER --json labels --jq '.labels[].name')
          REVIEWER="${{ github.repository_owner }}/translators"

          if [[ $LABELS == *"size/XS"* ]] || [[ $LABELS != *"size/"* ]]; then
            # Assuming 'webdoky/translators' is a team reviewer
            gh api repos/${{ github.repository }}/pulls/$PR_NUMBER/requested_reviewers -X DELETE -f team_reviewers[]=$REVIEWER
          else
            gh api repos/${{ github.repository }}/pulls/$PR_NUMBER/requested_reviewers -X POST -f team_reviewers[]=$REVIEWER
          fi
        env:
          GH_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
